#spring.application.name=webflux_board
spring:
  application:
    name: webflux_board
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password: qwer1234
#    password: 1234